### ISSUE TITLE
Chargers charge attack through barriers

### ISSUE THREAD

**Issue by MrSamsa** [Kenan2000/Secronom-Zombies#1]
Charger zombies are somehow attacking through walls with their charge attacks. I observed multiple chargers stuck inside vehicles or behind fences that were able to use the charge attack without actually passing through the barrier. The attack is devastating compared to a regular charger attack as it seems to cause the player character to bounce off everything near them rapidly, killing most characters in 1 attack.

I presume you can replicate by starting a game, spawning a charger behind a fence or inside a vehicle and approaching the sob. 

Thanks for keeping this mod around! 

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-6459-ge49eaa0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    <color_light_red>Secronom</color> [secronom],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    XEAS [XEAS],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    Cataclysm++ [Cata++],
    More Survivor Stuff [more_survivor_stuff],
    Mythical Martial Arts [MMA],
    No Rail Stations [No_Rail_Stations],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Cataclysm++ - UndeadPeople Tileset [Cata++UDP],
    DinoMod - UndeadPeople Tileset [DinoModUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    More Locations [more_locations],
    More Locations - UndeadPeople Tileset [more_locationsUDP],
    Secronom - UndeadPeople Tileset [secronom_UDP],
    Fuji's Military Profession Pack [fuji_mpp],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Kenan2000** [comment]
@MrSamsa I've just tested chargers' behavior after replacing `target_attack` with `projectile_attack`, they are definitely not one-shotting the character, the only weird behavior that I've not changed yet is bouncing - yeah, it makes the player character bounce around but it deals absolutely no damage to the character, I am on latest experimental - 11076, what experimental version you're on?Axema is still pondering about a possible solution, let's just consider their behavior WIP for now, but based on the tests it is definitely not as dangerous as one-shot behavior - it does not one-shot at all

And no problem, a pleasure to keep this project going, Axema might be coming back at some point to work some more on it, I am just maintaining it

**Comment by MrSamsa** [comment]
It seems like the damage I witnessed was probably due to being inside a vehicle. After being stunned by the chargers attack through the walls the character must have been killed from being thrown around the moving vehicle. 

Sorry for any confusion and thanks again.

**Comment by Kenan2000** [comment]
Oh that changes everything then, I will remove the pull spell that does the character bouncing then, this is quite a serious issue, thank you for notifying about it

**Comment by Kenan2000** [comment]
@MrSamsa Updated it and tested, it works now more or less well without making the player bounce like crazy, feel free to test it :-)

**Comment by Kenan2000** [comment]
Will publish an update for spells revamp update today, vanilla JSON has been updated and it basically broke the old spells JSON format rendering it useless, working...
