### ISSUE TITLE
Charger zombies can charge while stuck in a bear trap

### ISSUE THREAD

**Issue by SuddenEyePuncture** [Kenan2000/Secronom-Zombies#23]
I've caught a charger zombie in a bear trap. When I decided to get closer, the zombie charged while still being stuck in a trap. Upon examining the zombie after charge it was still stuck and couldn't move. After death it dropped the bear trap, as normal.

Probably charger zombies shouldn't be able to charge while stuck in a bear trap.

Alternatively they should free themselves while leaving a snapped bear trap behind.

Platform     : Windows_x64
Graphics     : Tiles
Build number : #11581
Build version: 0.E-10395-g4525b4f

Mods:
  "dda",
  "no_npc_food",
  "package_bionic_professions",
  "BL9_100monres",
  "secronom",
  "secronom_lore_expansion",
  "aftershock",
  "blazeindustries",
  "wandering_masters",
  "no_hope",
  "Bug's life",
  "MMA",
  "Dorf_Life",
  "Tankmod_Revived",
  "No_Fungi",
  "Craftable mech batteries",
  "useful_helicopters",
  "Useful ramps"

**Comment by AxemaVales** [comment]
Sorry for late reply but, I can't seem to find a solution for this bug. The charger zombie uses a chain of spells to perform a charge attack, and as long as it has a target in its range, it will charge regardless of movement-impairing effects it has.

Thanks 👍
