### ISSUE TITLE
Bug during character creation

### ISSUE THREAD

**Issue by Nephelos** [Kenan2000/Secronom-Zombies#25]
DEBUG    : (json-error)
Json error: data/mods/secronom/Modification_Files/Items/secro_guns.json:354:13: Invalid or misplaced field name "burst" in JSON data

    "dispersion": 170,
    "durability": 6,
    "burst":
            ^
             10,
    "pocket_data": [
      {

 FUNCTION : void JsonObject::report_unvisited() const
 FILE     : src/json.cpp
 LINE     : 122
 VERSION  : 6616372

Experimental version (Build 2021 07 04 1015/Version 6616372 (tiles))

**Comment by Nephelos** [comment]
I dont want to open multiple issues so here we go again (sorry about that): 

 DEBUG    : Wheel 'secro_flesh_wheel_leg' lacks either 'UNSTABLE_WHEEL' or 'STABLE' flag.

 FUNCTION : static void vpart_info::check()
 FILE     : src/veh_type.cpp
 LINE     : 763
 VERSION  : 1ddd145

Experimental version: 1ddd145 (tiles) / Build: 2021-07-04-1244

**Comment by AxemaVales** [comment]
I fixed the second issue by removing them (they're unused vehicle parts) but for the first issue, I can't do a fix for it atm.
@Kenan2000 could help you out with this :+1:

**Comment by Nephelos** [comment]
Thanks axema 😊

**Comment by AxemaVales** [comment]
@Nephelos first bug have been fixed by kenan 👍

**Comment by Nephelos** [comment]
Its nice to see that both of you working hard to fix new bugs 😊. The Mi-Go Friendship Society approves your work ❤
