### ISSUE TITLE
CBM harvest groups not define in vanilla anymore

### ISSUE THREAD

**Issue by DenJur** [Kenan2000/Secronom-Zombies#28]
Looks like base CDDA no longer allows CBM harvest from corpses so harvest groups were removed. I suppose mod either needs to define theirown or dependency on Aftershock (still defines those groups) if that's the indended dependency or remove harvest inline with vanilla.

DEBUG    : monster mon_sflesh_zombie_brute_shocker has invalid harvest_entry: CBM_SUBS

 FUNCTION : void MonsterGenerator::check_monster_definitions() const
 FILE     : src/monstergenerator.cpp
 LINE     : 1192
 VERSION  : 0.F-876-g745cc115de

**Comment by AxemaVales** [comment]
Issue was resolved. Update the mod for the fix :+1:
