### ISSUE TITLE
Nest placement bounds checking

### ISSUE THREAD

**Issue by waveyl** [Kenan2000/Secronom-Zombies#33]
DEBUG    : nest SecronomSSBunker_nest_bloodmess within mapgen SecronomSSBunker can place something at x = 24, which is in a different OMT from the smallest nest origin (20, 9), and could lead to an out of bounds placement

 FUNCTION : virtual void jmapgen_nested::check(const string&, const mapgen_parameters&, const jmapgen_int&, const jmapgen_int&) const
 FILE     : src/mapgen.cpp
 LINE     : 3301
 VERSION  : 04143c6

See https://github.com/CleverRaven/Cataclysm-DDA/pull/54682

**Comment by AxemaVales** [comment]
It's now fixed :+1:
