### ISSUE TITLE
 invalid spell id "mon_bot_secrolauncher_deploy_delay"

### ISSUE THREAD

**Issue by waveyl** [Kenan2000/Secronom-Zombies#35]
DEBUG    : invalid spell id "mon_bot_secrolauncher_deploy_delay"

 FUNCTION : const T& generic_factory<T>::obj(const string_id<T>&) const [with T = spell_type]
 FILE     : src/generic_factory.h
 LINE     : 446
 VERSION  : f7c92b9

**Comment by linonetwo** [comment]
Is this a custom spell? I can't find it in https://github.com/CleverRaven/Cataclysm-DDA/pulls?q=mon_bot_secrolauncher_deploy_delay

**Comment by linonetwo** [comment]
But I can't find https://github.com/CleverRaven/Cataclysm-DDA/search?q=mon_bot_secroinforcer_target_random too.
