### ISSUE TITLE
need to specify covered limbs for each body part

### ISSUE THREAD

**Issue by waveyl** [Kenan2000/Secronom-Zombies#38]
DEBUG    : Error: Json error: data/mods/Kenan-Modpack-Chinese/secronom_lore_expansion/Modification Files/Items/Armors/secro_power_armor_flesh_addons.json:34:5: need to specify covered limbs for each body part

        "coverage": 0
      }
    ]
    ^

  },
  {

 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 787
 VERSION  : 5ba62ff

**Comment by waveyl** [comment]
see https://github.com/CleverRaven/Cataclysm-DDA/pull/55939

**Comment by YuPro** [comment]
It's savebreaking issue and secro_power_armor_flesh_addons.json is not only file that don't have "covers" values (2 lines there). 
At least secro_power_armor_modules.json don't have them too (lines: 42, 91, 134, 165, 221, 252, 301, 332, 373).
Didn't check all files, but I'm suspicious that almost all armor files have such lines.

**Comment by Kenan2000** [comment]
Hopefully fixed in latest update
