### ISSUE TITLE
secronom bunker mapgen and invalid spell error

### ISSUE THREAD

**Issue by Maryionet** [Kenan2000/Secronom-Zombies#42]
![Screenshot_2022-05-06-16-17-47-25_6fe8938556442e3d4f710ab4f9a16601](https://user-images.githubusercontent.com/68288642/167094455-f5e6b880-63c4-4c5a-bf1e-d863de3c013a.jpg)
![Screenshot_2022-05-06-16-16-30-37_6fe8938556442e3d4f710ab4f9a16601](https://user-images.githubusercontent.com/68288642/167094467-d5315ea2-575a-4e95-b5dc-935a9bc7c2a3.jpg)

**Comment by Maryionet** [comment]
Btw the mapgen error appears when the expansion pack is added

**Comment by kholat** [comment]
I have the same, how did you fix it?
