### ISSUE TITLE
Invalid monster flag: "FAT"

### ISSUE THREAD

**Issue by waveyl** [Kenan2000/Secronom-Zombies#45]
DEBUG    : Error: Json error: data/mods/Kenan-Modpack-Chinese/secronom/Modification_Files/Monsters/Abberations/Ayenel.json:72:7: invalid monster flag: "FAT"

      "ATTACKMON",
      "NO_BREATHE",
      "
      ^
       FAT",
      "PUSH_MON"
    ]

 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 926
 VERSION  : 57fe6ea

**Comment by WreckingAbandon** [comment]
I wonder how many other flags are invalid now, because before this "BONE" was invalid too.

**Comment by WreckingAbandon** [comment]
Other invalid flags I found were "LEATHER" and "GUILT", with the guilt flag for the youngins being replaced by a death function instead.

**Comment by waveyl** [comment]
Fixed in latest version.
