### ISSUE TITLE
Cant create char with secronom and other mods from Kenan pack

### ISSUE THREAD

**Issue by AlexisEssen** [Kenan2000/Secronom-Zombies#46]
Greetings, I returned to CDDA not so long ago, after a 7-9 months break and decided to instal some mods, but these two errors pop out and prevent me from creating new char, I am extremely bad at coding, so if someone can guide me through the process in fixing it, i would be very grateful. Sorry for offpost, i dont know where to post these..
![Скриншот 16-09-2022 190220](https://user-images.githubusercontent.com/43724648/190682108-06d93d06-9c98-4856-b311-48fd9853017b.jpg)
![Скриншот 16-09-2022 190238](https://user-images.githubusercontent.com/43724648/190682113-084a21d0-681b-49e4-925c-e6da5322e347.jpg)

**Comment by Wishbringer** [comment]
This is because of changes made to experimental from PR: https://github.com/CleverRaven/Cataclysm-DDA/commit/4840ee2e553ca74e14f3bbd624750cc51766ec8f

**Comment by Kenan2000** [comment]
Hopefully fixed in this update as well
