### ISSUE TITLE
Cannot load a world with Secronom+ Lore Expansion

### ISSUE THREAD

**Issue by zixq** [Kenan2000/Secronom-Zombies#47]
After a hiatus from CDDA, I switched and downloaded the Catapult launcher and after setting everything up and re-downloading various mods, including Secronom and its expansion, I tried to create a new world. However when the game tried to load Secronom+ Lore Expansion this error message popped up:
```
 DEBUG    : Error: tec_secro_morph_blades_slash_arc (class ma_technique) has two definitions from the same source (secronom_lore_expansion)!

 FUNCTION : new_character_tab
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\main_menu.cpp
 LINE     : 947
 VERSION  : 3d6730a
```
And game boots me to the main menu
I'm not quite sure what this means, I looked through the json briefly and found a file that has `tec_secro_morph_blades_slash_arc` and other techniques, but I couldn't tell why it was causing an error. I looked for duplicates of code or something but found nothing. It only shows up when I try to load a world (old or new) that has Secronom+ Lore Expansion enabled.

**Comment by zixq** [comment]
Upon re-downloading the mod directly from the github (instead of downloading it through the launcher) it appears to have been fixed. I'm not sure if it was due to the launcher downloading a wrong version, or just an error on my part (could very well be the latter).

**Comment by Kenan2000** [comment]
@zixq Do not install or update mods using any launcher, download all mods manually correctly via GitHub, it is more reliable, more safe hopefully as well
