### ISSUE TITLE
flesh vessel spitter alt fire hangs the game with experimental

### ISSUE THREAD

**Issue by Nekojusan** [Kenan2000/Secronom-Zombies#50]
build type: windows-tiles-x64
build number: 2022-10-27-0619
commit sha: 41acb3011ffe6943bd949fd0d807a9da76f76509
commit url: https://github.com/CleverRaven/Cataclysm-DDA/commit/41acb3011ffe6943bd949fd0d807a9da76f76509

with this experimental attempting to use the flesh vessel spitter alt fire causes the game to hang 

![Secronom-Zombies spitter alt fire hang](https://user-images.githubusercontent.com/71791634/198581980-308a3b7d-1c35-4d81-afee-09f0b07975bf.JPG)
![Secronom-Zombies spitter alt fire hang 2](https://user-images.githubusercontent.com/71791634/198582022-4fa8b0a8-0726-49cb-b16b-dc8bdeb8c15c.JPG)

**Comment by Nekojusan** [comment]
[crash.log](https://github.com/Kenan2000/Secronom-Zombies/files/9888183/crash.log)

**Comment by Kenan2000** [comment]
@Nekojusan Hopefully fixed in this update as well
