### ISSUE TITLE
Invalid enchantment

### ISSUE THREAD

**Issue by waveyl** [Kenan2000/Secronom-Zombies#54]
See #63629 of DDA
![image](https://user-images.githubusercontent.com/22638873/223649554-233232a5-0a9a-456f-9315-395d4d739dff.png)

**Comment by waveyl** [comment]
More:
ATTACK_COST 
ITEM_DAMAGE_AP in vamp_stuff

**Comment by waveyl** [comment]
More：
vehicle part vgen is not CARGO and cannot define size(blaze_mod)
vehicle part vgen2 is not CARGO and cannot define size(blaze_mod)

**Comment by Kenan2000** [comment]
@waveyl Hopefully fixed in this update as well
