### ISSUE TITLE
"Larva" tag no longer supported with latest experimental

### ISSUE THREAD

**Issue by ephemeralstoryteller** [Kenan2000/Secronom-Zombies#55]
A few creatures in insect-> saddler.json have the "larva" tag, which was recently deprecated. Game will refuse to load worlds with this mod when this tag remains.

**Fix**:
Deleting the tag allows the save to load normally.

Per [CleverRaven #63520](https://github.com/CleverRaven/Cataclysm-DDA/pull/63520#issue-1579739327), the "larva" tag was redundant and unnecessary, and thus there shouldn't be any issues with removing this tag.

**Comment by Kenan2000** [comment]
Hopefully fixed in this update as well
