### ISSUE TITLE
Proficency Error

### ISSUE THREAD

**Issue by ephemeralstoryteller** [Kenan2000/Secronom-Zombies#56]
On load, get this error:

![secro-error](https://user-images.githubusercontent.com/11377530/226984287-e6ea153d-6b8d-4d3d-8e7b-8e29ea44b107.png)

Proposed fix: 
According to https://github.com/CleverRaven/Cataclysm-DDA/pull/64079#issue-1617491728, this should just be a name swap.

**Comment by Kenan2000** [comment]
Hopefully fixed in this update as well

**Comment by ephemeralstoryteller** [comment]
Seems like both fixes worked, thank you!

**Comment by Kenan2000** [comment]
No problem
