### ISSUE TITLE
Secronum Mapgen weights crashing at world generation

### ISSUE THREAD

**Issue by Bill-Chompski** [Kenan2000/Secronom-Zombies#58]
This occurred on experimental build 2023-04-04-1402, using Secronum mod build be1d69f, both of which are their most recent version at time of posting

This error occurs on world generation.
[This is a screenshot of the error](https://i.imgur.com/eVmHyrs.png)

Debug log report is below.

`17:53:42.302 ERROR : src/generic_factory.h:479 [int_id<T> generic_factory<T>::convert(const string_id<T>&, const int_id<T>&, bool) const [with T = ter_t]] invalid terrain id "t_console_broken"
17:53:43.293 ERROR : src/generic_factory.h:479 [int_id<T> generic_factory<T>::convert(const string_id<T>&, const int_id<T>&, bool) const [with T = ter_t]] invalid terrain id "t_machinery_heavy"
17:53:43.293 ERROR : src/generic_factory.h:479 [int_id<T> generic_factory<T>::convert(const string_id<T>&, const int_id<T>&, bool) const [with T = ter_t]] invalid terrain id "t_machinery_light"
17:53:44.047 ERROR : src/main_menu.cpp:974 [bool main_menu::new_character_tab()] Error: Json error: data/mods/Secronom-Zombies-master/secronom/Modification_Files/Maps/Flesh/flesh_buildings.json:1178:14: format: rows: row 7 column 19: '%' is not in 'terrain', and no 'fill_ter' is set!

    "weight": 750,
    "object": {
      "rows":
             ^
              [
        "ssssssssssssssssssssssss",
        "ssWWWWWWWWssssssssssssss",

17:54:34.178 : Log shutdown.`

**Comment by Kenan2000** [comment]
@Bill-Chompski Hopefully fixed in this update as well
