### ISSUE TITLE
unrecognized number source in {"skil1":"dodge" "u_val":'skill_level"}

### ISSUE THREAD

**Issue by waveyl** [Kenan2000/Secronom-Zombies#60]
See #65465
![image](https://user-images.githubusercontent.com/22638873/236655417-47bc97c2-ed7a-42c9-9b0d-c9e4b6d17554.png)
![image](https://user-images.githubusercontent.com/22638873/236655411-622f6cee-8daf-4e62-9e8d-8456ee9eef45.png)

**Comment by AxemaVales** [comment]
On it :+1:

**Comment by AxemaVales** [comment]
:+1:
