### ISSUE TITLE
Segmentation Fault crash on killing certain enemies

### ISSUE THREAD

**Issue by Carrnage** [Kenan2000/Secronom-Zombies#61]
When i kill the "Flesh" boss enemies in the flesh tower and in the Secronom added caves the game crashes with a segmentation fault
[crash.log](https://github.com/Kenan2000/Secronom-Zombies/files/11469187/crash.log)

**Comment by AxemaVales** [comment]
I haven't tested them for a long while so thanks for notifying me about this. I'm currently planning on reworking some locations and I hope this gets fixed along with it.
