### ISSUE TITLE
Error on world load

### ISSUE THREAD

**Issue by Enderlordalatreon** [Kenan2000/Secronom-Zombies#62]
DEBUG    : Error: Json error: mods/secronom/Modification_Files/Monsters/-Essentials/secro_magic_trans_eoc.json:11:33: unrecognized number source in { "id": "mon_zombie", "radius": 0, "u_val": "monsters_nearby" }

          "condition": {
            "or": [
              { "compare_num": [
                                ^
                                 { "u_val": "monsters_nearby", "id": "mon_zombie", "radius": 0 }, "==", { "const": 1 } ] },
              {
                "compare_num": [ { "u_val": "monsters_nearby", "id": "mon_zombie_resort_dancer", "radius": 0 }, "==", { "const": 1 } 

 FUNCTION : new_character_tab
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\main_menu.cpp
 LINE     : 983
 VERSION  : 75fbb0d

Going to assume it's not compatible with the latest experimental, will try the latest stable.
>Screenshot of error
![Screenshot 2023-06-22 210131](https://github.com/Kenan2000/Secronom-Zombies/assets/66154890/393d8d23-bbef-4a0c-9819-70aceff863b5)

**Comment by Kenan2000** [comment]
Hopefully fixed in this update as well
