### ISSUE TITLE
Invalid special_attacks

### ISSUE THREAD

**Issue by waveyl** [Kenan2000/Secronom-Zombies#63]
![image](https://github.com/Kenan2000/Secronom-Zombies/assets/22638873/a298a867-6865-4723-821e-af34e7013bc0)

**Comment by Kenan2000** [comment]
@waveyl Hopefully fixed in this update as well

**Comment by waveyl** [comment]
![image](https://github.com/Kenan2000/Secronom-Zombies/assets/22638873/ddc6886e-6367-43c6-8082-bcfe300b76ee)
There are still somes

**Comment by Kenan2000** [comment]
@waveyl Hopefully fixed in this update as well
