### ISSUE TITLE
Old json settings

### ISSUE THREAD

**Issue by 9ghtX** [Kenan2000/Secronom-Zombies#64]
On 0.G CDDA version Secronom throws fatal error with wrong materials' resist. It seems like devs changed json structure so you need to change it, otherwise mod won't load.

```
DEBUG    : Error: Json error: C:/Games/Cataclysm DDA/dda/userdata/mods/secronom/Modification_Files/Items/-Essentials/secro_mat.json:1:2: missing mandatory member "bash_resist"

[
 ^
  {
    "type": "material",
    "id": "secro_null",


 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 986
 VERSION  : d6ec466
```

**Comment by Kenan2000** [comment]
@9ghtX With regards to CDDA version of Axema's Secronom mod Axema updates whereas I try to maintain Axema's Secronom mod hopefully only for latest experimental versions so if you want to play with Axema's Secronom mod you need to download CDDA latest experimental versions
