### ISSUE TITLE
Invalid or misplaced field name "countdown_destroy"in json data

### ISSUE THREAD

**Issue by waveyl** [Kenan2000/Secronom-Zombies#65]
![image](https://github.com/Kenan2000/Secronom-Zombies/assets/22638873/e9f65e28-7f12-47d5-82a8-2b5465e7c65d)

**Comment by waveyl** [comment]
![image](https://github.com/Kenan2000/Secronom-Zombies/assets/22638873/b7e9f66c-d81e-46c4-afb6-60871c60e43c)
In secronom\Modification_Files\Monsters\Zombies\Revenant.json

**Comment by waveyl** [comment]
![image](https://github.com/Kenan2000/Secronom-Zombies/assets/22638873/61c1321f-da3f-40b9-bb95-9b7081f497c6)

**Comment by waveyl** [comment]
See #66386
![image](https://github.com/Kenan2000/Secronom-Zombies/assets/22638873/34282091-6283-471c-99a9-853e146fad7e)

**Comment by Kenan2000** [comment]
Hopefully fixed in this update as well
