### ISSUE TITLE
A bunch of things that need fixes

### ISSUE THREAD

**Issue by SurFlurer** [Kenan2000/Secronom-Zombies#66]
Logs are collected from loading secronom on `cata_test` built from DDA's latest master.

Thanks for maintaining this great mod!
<details><summary>Details</summary>
<p>

(dda,secronom)=>(continued from above) ERROR : src/flexbuffer_json.cpp:341 [void JsonObject::error_skipped_members(const std::vector<size_t> &) const] (json-error)
Error: (dda,secronom)=>Invalid or misplaced field name "no_deactivate_msg" in JSON data

      "sound_volume": 0,
      "sound_msg": "Tick.",
      "no_deactivate_msg": "It's no use!",
                         ▲▲▲
      "explosion": { "power": 75 }
    },

(dda,secronom)=>12:58:39.887 ERROR : src/flexbuffer_json.cpp:341 [void JsonObject::error_skipped_members(const std::vector<size_t> &) const] (json-error)
Error: (dda,secronom)=>Invalid or misplaced field name "sound_msg" in JSON data

      "draw_explosion_color": "red",
      "sound_volume": 0,
      "sound_msg": "Tick.",
                 ▲▲▲
      "no_deactivate_msg": "It's no use!",
      "explosion": { "power": 75 }

(dda,secronom)=>12:58:39.888 ERROR : src/flexbuffer_json.cpp:341 [void JsonObject::error_skipped_members(const std::vector<size_t> &) const] (json-error)
Error: (dda,secronom)=>Invalid or misplaced field name "sound_volume" in JSON data

      "draw_explosion_radius": 2,
      "draw_explosion_color": "red",
      "sound_volume": 0,
                    ▲▲▲
      "sound_msg": "Tick.",
      "no_deactivate_msg": "It's no use!",

(dda,secronom)=>12:58:39.888 ERROR : src/flexbuffer_json.cpp:341 [void JsonObject::error_skipped_members(const std::vector<size_t> &) const] (json-error)
Error: (dda,secronom)=>Invalid or misplaced field name "no_deactivate_msg" in JSON data

      "sound_volume": 0,
      "sound_msg": "*splat*",
      "no_deactivate_msg": "*splat* *splat*",
                         ▲▲▲
      "draw_explosion_color": "green",
      "fields_type": "fd_relinquished_revive",

(dda,secronom)=>12:58:39.889 ERROR : src/flexbuffer_json.cpp:341 [void JsonObject::error_skipped_members(const std::vector<size_t> &) const] (json-error)
Error: (dda,secronom)=>Invalid or misplaced field name "sound_msg" in JSON data

      "type": "explosion",
      "sound_volume": 0,
      "sound_msg": "*splat*",
                 ▲▲▲
      "no_deactivate_msg": "*splat* *splat*",
      "draw_explosion_color": "green",

(dda,secronom)=>12:58:39.889 ERROR : src/flexbuffer_json.cpp:341 [void JsonObject::error_skipped_members(const std::vector<size_t> &) const] (json-error)
Error: (dda,secronom)=>Invalid or misplaced field name "sound_volume" in JSON data

    "drop_action": {
      "type": "explosion",
      "sound_volume": 0,
                    ▲▲▲
      "sound_msg": "*splat*",
      "no_deactivate_msg": "*splat* *splat*",

(dda,secronom)=>12:58:39.890 ERROR : src/flexbuffer_json.cpp:341 [void JsonObject::error_skipped_members(const std::vector<size_t> &) const] (json-error)
Error: (dda,secronom)=>Invalid or misplaced field name "no_deactivate_msg" in JSON data

      "sound_volume": 0,
      "sound_msg": "*splat*",
      "no_deactivate_msg": "*splat* *splat*",
                         ▲▲▲
      "draw_explosion_color": "red",
      "fields_type": "fd_sflesh",

(dda,secronom)=>12:58:39.890 ERROR : src/flexbuffer_json.cpp:341 [void JsonObject::error_skipped_members(const std::vector<size_t> &) const] (json-error)
Error: (dda,secronom)=>Invalid or misplaced field name "sound_msg" in JSON data

      "type": "explosion",
      "sound_volume": 0,
      "sound_msg": "*splat*",
                 ▲▲▲
      "no_deactivate_msg": "*splat* *splat*",
      "draw_explosion_color": "red",

(dda,secronom)=>12:58:39.890 ERROR : src/flexbuffer_json.cpp:341 [void JsonObject::error_skipped_members(const std::vector<size_t> &) const] (json-error)
Error: (dda,secronom)=>Invalid or misplaced field name "sound_volume" in JSON data

    "drop_action": {
      "type": "explosion",
      "sound_volume": 0,
                    ▲▲▲
      "sound_msg": "*splat*",
      "no_deactivate_msg": "*splat* *splat*",

(dda,secronom)=>12:58:39.891 ERROR : src/flexbuffer_json.cpp:341 [void JsonObject::error_skipped_members(const std::vector<size_t> &) const] (json-error)
Error: (dda,secronom)=>Invalid or misplaced field name "no_deactivate_msg" in JSON data

      "sound_volume": 0,
      "sound_msg": "*splat*",
      "no_deactivate_msg": "*splat* *splat*",
                         ▲▲▲
      "draw_explosion_color": "red",
      "fields_type": "fd_sflesh_heap_death",

(dda,secronom)=>12:58:39.891 ERROR : src/flexbuffer_json.cpp:341 [void JsonObject::error_skipped_members(const std::vector<size_t> &) const] (json-error)
Error: (dda,secronom)=>Invalid or misplaced field name "sound_msg" in JSON data

      "type": "explosion",
      "sound_volume": 0,
      "sound_msg": "*splat*",
                 ▲▲▲
      "no_deactivate_msg": "*splat* *splat*",
      "draw_explosion_color": "red",

(dda,secronom)=>12:58:39.891 ERROR : src/flexbuffer_json.cpp:341 [void JsonObject::error_skipped_members(const std::vector<size_t> &) const] (json-error)
Error: (dda,secronom)=>Invalid or misplaced field name "sound_volume" in JSON data

    "drop_action": {
      "type": "explosion",
      "sound_volume": 0,
                    ▲▲▲
      "sound_msg": "*splat*",
      "no_deactivate_msg": "*splat* *splat*",

(dda,secronom)=>12:58:39.892 ERROR : src/flexbuffer_json.cpp:341 [void JsonObject::error_skipped_members(const std::vector<size_t> &) const] (json-error)
Error: (dda,secronom)=>Invalid or misplaced field name "no_deactivate_msg" in JSON data

      "sound_volume": 0,
      "sound_msg": "*splat*",
      "no_deactivate_msg": "*splat* *splat*",
                         ▲▲▲
      "draw_explosion_color": "green",
      "fields_type": "fd_shifter_shift",

(dda,secronom)=>12:58:39.892 ERROR : src/flexbuffer_json.cpp:341 [void JsonObject::error_skipped_members(const std::vector<size_t> &) const] (json-error)
Error: (dda,secronom)=>Invalid or misplaced field name "sound_msg" in JSON data

      "type": "explosion",
      "sound_volume": 0,
      "sound_msg": "*splat*",
                 ▲▲▲
      "no_deactivate_msg": "*splat* *splat*",
      "draw_explosion_color": "green",

(dda,secronom)=>12:58:39.893 ERROR : src/flexbuffer_json.cpp:341 [void JsonObject::error_skipped_members(const std::vector<size_t> &) const] (json-error)
Error: (dda,secronom)=>Invalid or misplaced field name "sound_volume" in JSON data

    "drop_action": {
      "type": "explosion",
      "sound_volume": 0,
                    ▲▲▲
      "sound_msg": "*splat*",
      "no_deactivate_msg": "*splat* *splat*",

(dda,secronom)=>12:58:39.941 ERROR : src/monstergenerator.cpp:1390 [void mtype::add_special_attack(const JsonObject &, const std::string &)] mon_insect_saddler_brute specifies more than one attack of (sub)type leap, ignoring all but the last
(dda,secronom)=>12:58:39.941 ERROR : src/monstergenerator.cpp:1390 [void mtype::add_special_attack(const JsonObject &, const std::string &)] mon_insect_saddler_scout specifies more than one attack of (sub)type leap, ignoring all but the last
(dda,secronom)=>12:58:39.950 ERROR : src/monstergenerator.cpp:1390 [void mtype::add_special_attack(const JsonObject &, const std::string &)] mon_zombie_fleshknot_weak specifies more than one attack of (sub)type gun, ignoring all but the last
(dda,secronom)=>12:58:39.950 ERROR : src/monstergenerator.cpp:1390 [void mtype::add_special_attack(const JsonObject &, const std::string &)] mon_zombie_fleshknot_mode specifies more than one attack of (sub)type gun, ignoring all but the last
(dda,secronom)=>12:58:39.950 ERROR : src/monstergenerator.cpp:1390 [void mtype::add_special_attack(const JsonObject &, const std::string &)] mon_zombie_fleshknot_stro specifies more than one attack of (sub)type gun, ignoring all but the last
(dda,secronom)=>12:58:39.950 ERROR : src/monstergenerator.cpp:1390 [void mtype::add_special_attack(const JsonObject &, const std::string &)] mon_zombie_fleshknot_vstro specifies more than one attack of (sub)type gun, ignoring all but the last
(dda,secronom)=>12:58:39.969 ERROR : src/monstergenerator.cpp:1390 [void mtype::add_special_attack(const JsonObject &, const std::string &)] mon_sflesh_centipede_mom specifies more than one attack of (sub)type spell, ignoring all but the last
(dda,secronom)=>12:58:39.970 ERROR : src/monstergenerator.cpp:1390 [void mtype::add_special_attack(const JsonObject &, const std::string &)] mon_sflesh_spider_cellar_mega specifies more than one attack of (sub)type spell, ignoring all but the last
(dda,secronom)=>12:58:39.980 ERROR : src/monstergenerator.cpp:1390 [void mtype::add_special_attack(const JsonObject &, const std::string &)] mon_sflesh_zombie_wretch specifies more than one attack of (sub)type spell, ignoring all but the last
(dda,secronom)=>12:58:39.982 ERROR : src/monstergenerator.cpp:1390 [void mtype::add_special_attack(const JsonObject &, const std::string &)] mon_sflesh_boomer_glutton specifies more than one attack of (sub)type spell, ignoring all but the last
(dda,secronom)=>12:58:39.982 ERROR : src/monstergenerator.cpp:1390 [void mtype::add_special_attack(const JsonObject &, const std::string &)] mon_sflesh_boomer_claymore specifies more than one attack of (sub)type spell, ignoring all but the last
(dda,secronom)=>12:58:39.983 ERROR : src/monstergenerator.cpp:1390 [void mtype::add_special_attack(const JsonObject &, const std::string &)] mon_sflesh_zombie_phase_skulker specifies more than one attack of (sub)type spell, ignoring all but the last
(dda,secronom)=>12:58:39.983 ERROR : src/monstergenerator.cpp:1390 [void mtype::add_special_attack(const JsonObject &, const std::string &)] mon_sflesh_zombie_phase_shrike specifies more than one attack of (sub)type spell, ignoring all but the last
(dda,secronom)=>12:58:39.987 ERROR : src/monstergenerator.cpp:1390 [void mtype::add_special_attack(const JsonObject &, const std::string &)] mon_sflesh_frog_mother specifies more than one attack of (sub)type spell, ignoring all but the last
(dda,secronom)=>12:58:39.988 ERROR : src/monstergenerator.cpp:1390 [void mtype::add_special_attack(const JsonObject &, const std::string &)] mon_sflesh_zombie_crawler_pupa specifies more than one attack of (sub)type spell, ignoring all but the last
(dda,secronom)=>12:58:39.988 ERROR : src/monstergenerator.cpp:1390 [void mtype::add_special_attack(const JsonObject &, const std::string &)] mon_sflesh_zombie_pupa specifies more than one attack of (sub)type spell, ignoring all but the last
(dda,secronom)=>12:58:39.988 ERROR : src/monstergenerator.cpp:1390 [void mtype::add_special_attack(const JsonObject &, const std::string &)] mon_sflesh_hulk_pupa specifies more than one attack of (sub)type spell, ignoring all but the last
(dda,secronom)=>12:58:39.988 ERROR : src/monstergenerator.cpp:1390 [void mtype::add_special_attack(const JsonObject &, const std::string &)] mon_sflesh_zombie_pupa_shady specifies more than one attack of (sub)type spell, ignoring all but the last
(dda,secronom)=>12:58:44.607 ERROR : src/monstergenerator.cpp:1390 [void mtype::add_special_attack(const JsonObject &, const std::string &)] mon_sflesh_brute_pupa specifies more than one attack of (sub)type spell, ignoring all but the last
(dda,secronom)=>12:58:49.315 ERROR : src/mapgen.cpp:1212 [virtual void mapgen_value<string_id<VehicleGroup>>::id_source::check(const std::string &, const mapgen_parameters &) const [Id = string_id<VehicleGroup>]] mapgen 'nested mapgen mx_secro_ssf_nested' uses invalid entry 'secro_veh_sscarrier'
(dda,secronom)=>12:58:49.315 ERROR : src/vehicle_group.cpp:40 [const VehicleGroup &string_id<VehicleGroup>::obj() const [T = VehicleGroup]] invalid vehicle group id secro_veh_sscarrier
(dda,secronom)=>12:58:49.315 ERROR : src/mapgen.cpp:2657 [virtual void jmapgen_vehicle::check(const std::string &, const mapgen_parameters &, const jmapgen_int &, const jmapgen_int &) const] In nested mapgen mx_secro_ssf_nested, vehicle placement at x:[12,12], y:[10,10]: potential placement of vehicle out of bounds.  At rotation 270 the vehicle [vgroup_id ; vproto_id ] extends too far west, reaching coordinate x = -2147483636 (should be at least 0)
(dda,secronom)=>12:58:49.315 ERROR : src/mapgen.cpp:1212 [virtual void mapgen_value<string_id<VehicleGroup>>::id_source::check(const std::string &, const mapgen_parameters &) const [Id = string_id<VehicleGroup>]] mapgen 'nested mapgen mx_secro_ssb_nested' uses invalid entry 'secro_veh_sscarrier'
(dda,secronom)=>12:58:49.315 ERROR : src/vehicle_group.cpp:40 [const VehicleGroup &string_id<VehicleGroup>::obj() const [T = VehicleGroup]] invalid vehicle group id secro_veh_sscarrier
(dda,secronom)=>12:58:49.315 ERROR : src/mapgen.cpp:2657 [virtual void jmapgen_vehicle::check(const std::string &, const mapgen_parameters &, const jmapgen_int &, const jmapgen_int &) const] In nested mapgen mx_secro_ssb_nested, vehicle placement at x:[12,12], y:[10,10]: potential placement of vehicle out of bounds.  At rotation 270 the vehicle [vgroup_id ; vproto_id ] extends too far west, reaching coordinate x = -2147483636 (should be at least 0)

</p>
</details>

**Comment by Kenan2000** [comment]
@SurFlurer, @waveyl  I have fixed most of these errors except for ones that mention in-game more than one monster special attack or spell which I have no intentions to fix, like I have already explained to wave, because that is the original intention in mods for these in-game monsters to have more than one monster special attack or spell clearly. Hmm, so developers themselves need to add support to multiple in-game monsters special attacks along with spells so that these errors would be fixed hopefully

**Comment by SurFlurer** [comment]
You may also wanna fix the `flesh_tendril` special attack changed by https://github.com/CleverRaven/Cataclysm-DDA/pull/65774 or the game would CTD when failing to find `grab` and `ranged_pull` special attacks. I'm not sure there's much to do to fix this on DDA side, besides maybe docs should display the usage of this special attack more clearly.

**Comment by Kenan2000** [comment]
@SurFlurer Hopefully fixed in this update as well

**Comment by Kenan2000** [comment]
No problem
