### ISSUE TITLE
mon_feral_diver_knife has been removed in #67707

### ISSUE THREAD

**Issue by waveyl** [Kenan2000/Secronom-Zombies#67]
![image](https://github.com/Kenan2000/Secronom-Zombies/assets/22638873/3e545377-d409-4824-a19f-8b132f1cd5b5)

**Comment by waveyl** [comment]
Invalid item_group_id "ammo_casings_bulk" in mapgen s_shop_flesh

**Comment by waveyl** [comment]
no such item group "mil_hw"
Obsolete in #67646

**Comment by Kenan2000** [comment]
@waveyl Hopefully fixed in this update as well
